### PR TITLE
Typos and Wording

### PR DESCRIPTION
**Pull request by JakobMiksch**
- based on #10 
- addresses some typos and wording.

### CODE REVIEW

**Review by dnlkoch — APPROVED** [review]

**Comment by dnlkoch** [comment]
Could you please rebase the `meggsimum:ter-update-content` branch against the current `main`?

**Comment by dnlkoch** [comment]
Could you please rebase the `meggsimum:ter-update-content` branch against the current `main`?

**Comment by JakobMiksch** [comment]
@dnlkoch I rebased the branch of this PR

**Review by dnlkoch — APPROVED** [review]

**Comment by dnlkoch** [comment]
Thanks @JakobMiksch!

**Pull request merged**
